// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: s1pb.proto

/*
Package s1pb is a generated protocol buffer package.

It is generated from these files:
	s1pb.proto

It has these top-level messages:
	Req
	Rsp
*/
package s1pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for S1 service

type S1Service interface {
	Call(ctx context.Context, in *Req, opts ...client.CallOption) (*Rsp, error)
}

type s1Service struct {
	c    client.Client
	name string
}

func NewS1Service(name string, c client.Client) S1Service {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "s1pb"
	}
	return &s1Service{
		c:    c,
		name: name,
	}
}

func (c *s1Service) Call(ctx context.Context, in *Req, opts ...client.CallOption) (*Rsp, error) {
	req := c.c.NewRequest(c.name, "S1.Call", in)
	out := new(Rsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for S1 service

type S1Handler interface {
	Call(context.Context, *Req, *Rsp) error
}

func RegisterS1Handler(s server.Server, hdlr S1Handler, opts ...server.HandlerOption) error {
	type s1 interface {
		Call(ctx context.Context, in *Req, out *Rsp) error
	}
	type S1 struct {
		s1
	}
	h := &s1Handler{hdlr}
	return s.Handle(s.NewHandler(&S1{h}, opts...))
}

type s1Handler struct {
	S1Handler
}

func (h *s1Handler) Call(ctx context.Context, in *Req, out *Rsp) error {
	return h.S1Handler.Call(ctx, in, out)
}
